### ISSUE TITLE
[Release] 0.9

### ISSUE THREAD

**Issue by HiddeLekanne** [Babylon-Development-Victoria-3/Victoria-3-Dev#328]
**Title:** [Release] 0.9

**Description:**
0.9 is a release for the 1.7.8. This includes a number of features. These features are listed in the acceptance criteria.

**Acceptance Criteria:**
# __**Update v0.9 Coming Soon**__
- We have hammered out over 500 bugs using a new scripting check implemented by our senior coder
- Further balance updates including-but-not-limited-to cheaper military goods (especially late game numbers), nerfs to base mobilization and upgrade speeds, Power Bloc Principles balance changes, subject interactions balance changes, subject tax nerf, lower base conversion and assimilation rates, law balance tweaks, and more!
- Nerfing and fixing up Britain/EIC JEs
- Journal and event fixes for Ottomans and Russia
- Frankfurt Conference less wonky, and post-unification more interactible to reduce penalties and set goals for German player.
- Labor Rights rework, with three additional laws and new ideological stances to reflect the balance of Unions vs Capital 
- Mobilization Options for Guns unlockable via a treaty, allowing the receiver to get potential access to advanced weaponry and reinforce potential proxy wars

**Additional Details:**
Checklist:

- [x] - Release on github
- [x] - Release on both steam workshops
- [x] - Publish announcement

**Priority:** High
**Estimated Effort:** Small

**Comment by RevoLou** [comment]
> Update on Imperia Mod v0.9:
> 
> Hello, and once again thank you for your patience. The mod team has been incredible hard at work, as well as developing tools to help us deal with things in a more efficient way. Some of the features for the last release before 1.8 officially drops are:
> 
> We have hammered out over 500 bugs using a new scripting check implemented by our senior coder, aiming to increase the overall stability of the game.
> Further balance updates including-but-not-limited-to cheaper military goods (especially late game numbers), nerfs to base mobilization and upgrade speeds, Power Bloc Principles balance changes, subject interactions balance changes, subject tax nerf, lower base conversion and assimilation rates, law balance tweaks, and more!
> A complete rebalance of Great Britain and East India Company's Journal Entries.
> Journal and event fixes for Ottomans and Russia.
> Frankfurt Conference has been fully reworked to be less wonky and including a brand new JE to deal with the debuffs post unification in an interactive way.
> Labor Rights rework, with three additional laws and new ideological stances to reflect the balance of Work vs Capital.
> Mobilization Options for Guns unlockable via a treaty, allowing the receiver to get potential access to advanced weaponry and reinforce potential proxy wars (Land Lease!).
> 
> The Pariah system overhaul, the Kurdistan update and Ottoman Sphere rework are still ongoing, and it is our hope to complete it as soon as possible, but due to a lack of manpower it has been delayed until someone on the team can properly develop it.



I believe this covers all topics on the issue as well as some that are not here, if anything needs changing let me know!

**Comment by HiddeLekanne** [comment]
Github release made https://github.com/Imperia-Development-Victoria-3/Imperia-Releases

**Comment by Danarca** [comment]
Uploaded to both workshop pages

**Comment by Danarca** [comment]
Also @RevoLou , I wouldn't call the Frankfurt Parliament stuff a "full" overhaul. There's some... slimming down, shall we say, of the main parliament, but else most of the work were on the post-unification "tanzimats"
